# Generated by Django 3.2.4 on 2021-06-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210605_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assed',
            new_name='Asset',
        ),
    ]
